version: 2.1

parameters:
  ssh-fingerprint:
    type: string
    default: "93:f8:51:53:5e:bd:75:0e:29:24:4d:6a:3f:ef:e1:4a"
  build-app1:
    type: boolean
    default: false
  build-app2:
    type: boolean
    default: false

orbs:
  vfcommon: voiceflow/common@dev:314875b74f82a896bf586464a898d09af6b6d226


# Reusable YAML chunks
defaults:
  ignore_staging_filters: &ignore_staging_filters
    branches:
      ignore:
        - staging


jobs:

  test: # Main unit, style, and dependency tests
    executor: vfcommon/node-executor
    steps: # a collection of executable commands
      - checkout
      - vfcommon/install_node_modules

  sleep: # sleep
    executor: vfcommon/node-executor
    steps: # a collection of executable commands
      - checkout
      - run: |
          yarn sleep



workflows:
  test-app1:
    when: << pipeline.parameters.build-app1 >>
    jobs:
      - test:
          context: dev-test
          filters:
            <<: *ignore_staging_filters

  test-app2:
    when: << pipeline.parameters.build-app2 >>
    jobs:
      - test:
          context: dev-test
          filters:
            <<: *ignore_staging_filters
 
  test-and-release:
    jobs:
      - test:
          context: dev-test
          filters:
            branches:
              only: master
