name: PR Title validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_run:
    workflows: ["Dependabot Trigger Workflow"]
    types: 
      - completed
jobs:
  pr-validation:
    name: Checks if the PR title is valid
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: ${{ secrets.PR_TITLE_REGEX }} # Regex the title should match.
          github_token: ${{ secrets.GH_SA_TOKEN }}